version: '3'

services:
  namenode:
    image: apache/hadoop:3.3.6
    container_name: namenode
    environment:
      - HADOOP_SERVICE=namenode
    ports:
      - "9870:9870"  # NameNode web UI
      - "8020:8020"  # NameNode RPC (fs.defaultFS)

  datanode:
    image: apache/hadoop:3.3.6
    container_name: datanode
    environment:
      - HADOOP_SERVICE=datanode
    depends_on:
      - namenode
    ports:
      - "9864:9864"  # DataNode web UI

  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
    command: >
      start.sh jupyter notebook --NotebookApp.token=''
      --NotebookApp.password=''
      --NotebookApp.disable_check_xsrf=True
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SPARK_VERSION=3.5.0
    depends_on:
      - namenode
      - datanode
  spark-master:
    image: bitnami/spark:3.5.6
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MASTER_WEBUI_PORT=8080

  spark-worker:
    image: bitnami/spark:3.5.6
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - "8081:8081"


volumes:
  hadoop_namenode:
  hadoop_datanode:
